### ISSUE TITLE
Diphascon release task list

### ISSUE THREAD

**Issue by cwgoes** [metastatedev/juvix#351]
Following [Ramazzottius](https://github.com/cryptiumlabs/juvix/issues/313). Proposed task-list. 

*Requisite components*

- [x] Full pipeline work: datatypes & pattern-matching (number 4 from https://github.com/cryptiumlabs/juvix/issues/352) (@andy-morris, @mariari @thealmarty @cwgoes to review)
  - Figure out a simpler way than Agda (initially)
  - Maybe look at mini-Agda
- [x] Start of termination/totality checker in separate repository (@thealmarty) (just be careful not to rely anything we don't plan to put in core)
- [x] Update Michelson parameterisation to use `morley` in `apply` (#386 ref https://github.com/cryptiumlabs/juvix/issues/330) (@mariari)
- [x] MVP arithmetic circuit that can compile simple circuits all the way from the frontend language - MVP 3 with testcases - https://github.com/cryptiumlabs/juvix/issues/171#issuecomment-601322574 (@cyberglot @cwgoes)
- [x] Language reference updates - https://github.com/cryptiumlabs/juvix/issues/253 (@cwgoes)

*Bonus components*

- [x] Add `let` to core (ref https://github.com/cryptiumlabs/juvix/issues/306) (@mariari)
- [ ] Research into type-theoretic questions on sub-usaging & unification of usages - https://github.com/cryptiumlabs/juvix/issues/46 (@andy-morris)
- [x] Research into compiling optimal reduction to stack machines - https://github.com/cryptiumlabs/juvix/issues/296 (@cwgoes)
- [ ] More complex example contracts in Idris/Agda/Coq/F* with mock stdlib - https://github.com/cryptiumlabs/juvix/issues/139, perhaps Uniswap & dominant assurance contract to start (@thealmarty)

**Comment by cwgoes** [comment]
Necessary remaining tasks before we can cut this release:
- [ ] Finalise test-cases & merge MVP circuit backend - https://github.com/metastatedev/juvix/pull/359 (@cyberglot)
- [ ] Contextualised frontend passes per https://github.com/metastatedev/juvix/issues/394 (@cyberglot @thealmarty)
- [ ] Basic datatypes & pattern-matching translation to Michelson per https://github.com/metastatedev/juvix/issues/405 (@cwgoes)

Bonus tasks:
- [ ] Datatype & pattern-match typechecking (@andy-morris)

Let's try to target the end of next week (June 26th).
