### ISSUE TITLE
Frontend => Core & Core => Core passes (list & tracking)

### ISSUE THREAD

**Issue by cwgoes** [metastatedev/juvix#390]
This issue intends to list a minimal set of passes for frontend to core.

- [Frontend AST](https://github.com/cryptiumlabs/juvix/blob/develop/src/Juvix/Frontend/Types.hs)
- [Core](https://github.com/cryptiumlabs/juvix/blob/develop/src/Juvix/Core/IR/Types/Base.hs)

Initial set:
- [ ] Convert frontend representation of datatypes & pattern-matching into the core representation of datatypes & pattern-matching
- [ ] Combine signature of function & function into annotated term
- [ ] Some pass extracts the main term and puts other definitions in a context for lookup
- [ ] Convert numbers & strings to backend-specific representation
- [ ] De-sugaring do & friends
- [ ] De-sugaring records
- [ ] De-sugaring modules into records
- [ ] Turn arrows into lambdas & appropriate types/usages
- [ ] De-sugar ifs into match/case
- [ ] De-sugar guards into match/case
- [ ] De-alias records
- [ ] Explicitize arguments (later: unification)
- [ ] De-sugar top level function usage annotation
- [ ] Deal with named types
- [ ] Deal with newtype declarations
- [ ] Deal with type aliases or desugar
- [ ] Renaming (hammer technique, eventually rapier technique)
- [ ] Compile datatypes / pattern matching to backend-specific operations (e.g. IF_LEFT)
- [ ] Inline all functions once compiled
  - [ ] Or maybe keep the context around? Not clear if safe
  - [ ] Determine which functions we can safely inline

Eventually:
- Deal properly with entrypoints to a smart contract
  - e.g. `#pragma entrypoint` above functions
- Add tuples as sugar for records
- Deal with locally opening modules
- Deal with universe levels

Internal representation: ordered set of definitions, compiled down.

Development process:
1. Write the types for all of the versions of core
    1. Extend extensible to deal with records
    1. Use extensible to do this
1. Decide upon an ordering of the process
1. Split up writing all of the passes
1. Frontend as extended core?
1. Also note any shortcuts taken on https://github.com/cryptiumlabs/juvix/issues/389

**Comment by cwgoes** [comment]
A more structured list is here - https://github.com/cryptiumlabs/juvix/issues/394.

**Comment by cwgoes** [comment]
Closing in favour of https://github.com/metastatedev/juvix/issues/394.
